site_name: My Docs
theme:
  name: material
  font: false
  nav:
  - Section:
    - section/index.md 
    - Page 1: section/page-1.md
    - Page 2: section/page-2.md
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
