site_name: AI Task Master
theme:
  name: material
  font: false
  nav:
  - Section:
    - Page 1: page-1.md
    - Page 2: page-2.md
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.sections
