site_name: AI Task Master
theme:
  name: material
  font: false
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  nav:
  - Section:
    - Page 1: page-1.md
    - Page 2: page-2.md
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.sections
plugins:
  - search
extra:
  homepage: https://kingsoftwaresolution.com/
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/srammu/
      name: King Koftware Solution on Github
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/
      name: King Software Solution on Facebook
copyright: Copyright &copy; 2023 - 2024 King Software Solution
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
