site_name: AI Task Master
theme:
  name: material
  font: false
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  nav:
  - Section:
    - Page 1: page-1.md
    - Page 2: page-2.md
  features:
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.sections
plugins:
  - search
extra:
  homepage: https://kingsoftwaresolution.com/
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/srammu/
      name: King Koftware Solution on Github
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/
      name: King Software Solution on Facebook
copyright: Copyright &copy; 2023 - 2024 King Software Solution
markdown_extensions:
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
