# Project information
site_name: AI Task Master
site_url: https://srammu.github.io/AITaskMaster/
site_author: Siddarudreswara Somashekar
site_description: >-
  AI-driven task prioritization Intelligent time estimation for tasks Personalized productivity insights and recommendations Integration with popular calendar and email services Collaborative features for team productivity

# Repository
repo_name: srammu/AITaskMaster
repo_url: https://github.com/srammu/AITaskMaster

# Copyright
copyright: Copyright &copy; 2023 - 2025 King Software Solution

# Configuration
theme:
  name: material
  #custom_dir: develop/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    #- navigation.path
    #- navigation.sections
    #- navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

# Plugins
plugins:
  - blog
  - social
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  #- minify:
      #minify_html: true

# Additional configuration
extra:
    status:
    new: Recently added
    deprecated: Deprecated
    analytics:
      provider: google
      property: !ENV GOOGLE_ANALYTICS_KEY
    homepage: https://kingsoftwaresolution.com/
    generator: false
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/srammu/
        name: King Koftware Solution on Github
      - icon: fontawesome/brands/facebook
        link: https://facebook.com/
        name: King Software Solution on Facebook

# Extensions
markdown_extensions:
  - tables
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  #- pymdownx.superfences:
      #custom_fences:
        #- name: mermaid
          #class: mermaid
          #format: !!python/name:pymdownx.superfences.fence_code_format
  #- pymdownx.tabbed:
      #alternate_style: true
      #combine_header_slug: true
      #slugify: !!python/object/apply:pymdownx.slugs.slugify
        #kwds:
          #case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Getting started: index.md
  - Start Your AITaskMaster Project:
    - develop/index.md
    - Set Up Your Development Environment: develop/development-environment.md
    - Design Your Database Schema: develop/design-db-scheme.md
    - Implement Core Backend Functionality: develop/backend-function.md
    - Develop the Frontend: develop/dev-frontend.md
    - Integrate AI Models: develop/integrate-ai.md
  - Testing and Deployment: test&deploy.md
  - Launch and Future Improvements: launch&Improve.md
  - User Feedback and Iteration: user-feedback.md
  - AI Ethics and Responsible Development: dev-ethics-responsible.md
  - The Future of AI-Powered Productivity: future-ai-prod.md
  - Join AITaskMaster 2.0 Beta Program: beta-prog.md
